"""first version

Revision ID: 38f5f66dd498
Revises: 
Create Date: 2023-06-08 12:36:05.497171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f5f66dd498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('gameroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_move', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('challenger', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_spawn_position', sa.String(), nullable=True),
    sa.Column('challenger_spaw_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['challenger'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameroom_id'), 'gameroom', ['id'], unique=False)
    op.create_table('gamerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_room', sa.Integer(), nullable=True),
    sa.Column('move_by', sa.Integer(), nullable=True),
    sa.Column('piece_move', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_room'], ['gameroom.id'], ),
    sa.ForeignKeyConstraint(['move_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamerecord_id'), 'gamerecord', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamerecord_id'), table_name='gamerecord')
    op.drop_table('gamerecord')
    op.drop_index(op.f('ix_gameroom_id'), table_name='gameroom')
    op.drop_table('gameroom')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
